version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data:
